name: flight_management_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  encrypted_shared_preferences: ^3.0.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  encrypt: ^5.0.0
  shared_preferences: ^2.0.6
  floor: ^1.4.0
  floor_generator: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
