name: flight_management_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:

  sdk: '>=3.2.3 <4.0.0'


  sdk: '3.3.4'



dependencies:
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  encrypt: ^5.0.0
  shared_preferences: ^2.0.6
  floor: ^1.4.0
  floor_generator: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  build_runner: ^2.1.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


flutter:
  uses-material-design: true

  assets:
    - assets/lang/

